//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int ID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string userDescription { get; set; }
        public string userPicture { get; set; }
        public string userFullName { get; set; }
        public string userAddress { get; set; }
    
        public virtual tblportfolio tblportfolio { get; set; }
    }
}
