//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portifolie_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class portifoliedbEntities : DbContext
    {
        public portifoliedbEntities(): base("name=portifoliedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbleducation> tbleducation { get; set; }
        public DbSet<tblportfolio> tblportfolio { get; set; }
        public DbSet<tbluser> tbluser { get; set; }
        public DbSet<tblwork> tblwork { get; set; }
    }
}
