//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portifolie_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblportfolio
    {
        public tblportfolio()
        {
            this.tbleducation = new HashSet<tbleducation>();
            this.tblwork = new HashSet<tblwork>();
        }
    
        public int ID { get; set; }
        public string portDescription { get; set; }
        public int userID { get; set; }
    
        public virtual ICollection<tbleducation> tbleducation { get; set; }
        public virtual tbluser tbluser { get; set; }
        public virtual ICollection<tblwork> tblwork { get; set; }
    }
}
