//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portifolie_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public tbluser()
        {
            this.tblportfolio = new HashSet<tblportfolio>();
        }
    
        public int ID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string userDescription { get; set; }
        public string userPicture { get; set; }
    
        public virtual ICollection<tblportfolio> tblportfolio { get; set; }
    }
}
