//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portifolie_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblwork
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> workStart { get; set; }
        public Nullable<System.DateTime> workFinish { get; set; }
        public string workName { get; set; }
        public string workTitle { get; set; }
        public string workReferenceName { get; set; }
        public string workReferenceNumber { get; set; }
        public int portID { get; set; }
    
        public virtual tblportfolio tblportfolio { get; set; }
    }
}
